### ISSUE TITLE
Error message for incorrect use of %

### ISSUE THREAD

**Issue by MacSplody** [loot/metadata-validator#3]
At the moment incorrect usage of % will display the following error.

> ERROR: boost::bad_format_string: format-string is ill-formed

Working version:

```yaml
  - &alreadyInX
    type: error
    content:
      - lang: en
        text: 'Delete. Already included in %1%.'
  - &alreadyInEnderalDLC
    <<: *alreadyInX
    subs: [ 'Enderal - Forgotten Stories.esm' ]
    condition: 'file("Enderal - Forgotten Stories.esm")'
```

Changes that will cause the error:

> 'Delete. Already included in 1%.'
or
> 'Delete. Already included in %1.'
or
> 'Delete. Already included in %1%%.'

So if possible we should show where the error is happening.
